# Generated by Django 4.2.6 on 2025-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('nascimento', models.DateField()),
                ('pesagens', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id_pesagem', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_pesagem', models.DateField()),
                ('peso', models.FloatField()),
            ],
        ),
    ]
